!!python/object:configs.config.Arguments

hosts:
- ["192.168.0.8", 502]

first_incoming:
  0
timestamp_addr:
  250

coil_addr:
  1ZYR5311: 100
  1ZYR5312: 101
  1ZYR1331: 102
  1ZYR2331: 103
  1ZSR5401A: 104
  1ZSR5401B: 105
  1ZYR5471: 106
  1ZYR5472: 107
  1AUTSTSQ_ON: 108
  T1_L52GX: 109
  T2_L52GX: 110
  1ZSO1117: 111
  1ZSO1116: 112
  1ZSO1026: 113
  1ZSO1021: 114
  1ZSO2117: 115
  1ZSO2116: 116
  1ZSO2026: 117
  1ZSO2021: 118
  1XS5907: 119
  S1_L52GX: 120
  T1_L83TMSEL: 121
  T2_L83TMSEL: 122
  1SEQ223B-DONE: 123
  1ZSO1145: 124
  1ZSO2145: 125
  1ZSO1175: 126
  1ZSO2175: 127
  1ZSO5062: 128
  T1_L83EX: 129
  T2_L83EX: 130
  1TV1118-Mode: 131
  1TV2118-Mode: 132
  1TV1025-Mode: 133
  1TV2025-Mode: 134
  1G1STSQ-LEAD: 135
  1G2STSQ-LEAD: 136
  S1_L4: 137
  1G1STSQ-RDY: 138
  1G2STSQ-RDY: 139
  1H1STSQ-RDY: 140
  1H2STSQ-RDY: 141
  1BOPSTSQ-RDY: 142
  1STRDY-STSQ: 143
  1ZSO1148: 144
  1ZSO2148: 145
  T1_L33MDCF: 146
  T1_L89SSC: 147
  T1_L86GLT1_EVT: 148
  T1_L86GLT3_EVT: 149
  T1_L33CB5C: 150
  T1_L33CB6C: 151
  T1_L33CB7C: 152
  T1_L33CB8C: 153
  T1_L4SS_RUN: 154
  T1_L86GLT7_EVT: 155
  T1_L28FD: 156
  T1_L3: 157
  T1_L4EX_SS: 158
  T1_L89NDO: 159
  T2_L89SSC: 160
  T2_L86GLT1_EVT: 161
  T2_L86GLT3_EVT: 162
  T2_L33CB5C: 163
  T2_L33CB6C: 164
  T2_L33CB7C: 165
  T2_L33CB8C: 166
  T2_L4SS_RUN: 167
  T2_L86GLT7_EVT: 168
  T2_L28FD: 169
  T2_L3: 170
  T2_L4EX_SS: 171
  T2_L89NDO: 172
  S1_L26SS_PER: 173
  S1_L83CVS_C: 174
  S1_L39DEAI: 175
  S1_L14HR: 176
  S1_L63IP_L_OK: 177
  S1_L26IS_L_OK: 178
  S1_L3CUST_PERM: 179
  S1_L33DRAIN_PER: 180
  S1_L30ECH_PER: 181
  S1_LLOAM: 182

reg_addr:
  1TY5904: 301
  T1_DWATT: 302
  T2_DWATT: 303
  S1_DWATT: 304
  1FI5301-TT: 305
  1FI5302-TT: 306
  1LI1100: 307
  1LI2100: 308
  1LI1130: 309
  1LI2130: 310
  1LI1160: 311
  1LI2160: 312
  S1_EV_P_SCA: 313
  1PI1100: 314
  1PI2100: 315
  1PI1130: 316
  1ZT1071: 317
  1ZT1001: 318
  1PI2130: 319
  1ZT2071: 320
  1ZT2001: 321
  1FT111-RATE: 322
  1FT211-RATE: 323
  1AIT1831: 324
  1AIT2831: 325
  1PT5015: 326
  1TI1118: 327
  1TI2118: 328
  1PI1001: 329
  1PI2001: 330
  1TI1025: 331
  1TI2025: 332
  1ZT1072: 333
  1ZT2072: 334
  1ZT1061: 335
  1ZT2061: 336
  1TI1177: 337
  1TI2177: 338
  1PI1061: 339
  016-01829-OUT: 340
  016-00288-OUT: 341
  1FI5301: 342
  1FI5302: 343
  1CCTIME: 344
  1AIT134-COMP: 345
  1AIT234-COMP: 346
  1AIT131-COMP: 347
  1AIT231-COMP: 348
  1TI132: 349
  1TI232: 350
  T1_TNH_V: 351
  T1_ttxm: 352
  T1_CTIMR1: 353
  T1_FQG: 354
  T1_L90PSEL_CMD: 355
  T1_FTG: 356
  T1_CTIM: 357
  T1_AFPEP: 358
  T2_TNH_V: 359
  T2_ttxm: 360
  T2_CTIMR1: 361
  T2_FQG: 362
  T2_L90PSEL_CMD: 363
  T2_FTG: 364
  T2_CTIM: 365
  T2_AFPEP: 366
  1STDL5477: 367
  S1_TNH_rpm: 368
  S1_IP_P: 369
  S1_TT_IS: 370
  S1_TT_1SBU1: 371
  S1_TT_1SBU2: 372
  S1_ECCENT: 373
  S1_TT_SSH: 374
  S1_V1_POS: 375
  S1_V1L_POS: 376
  S1_TT_LOCO: 377
  1STDL5472: 378
  1STDL5473: 379
  1STDL5474: 380
  1STDL5475: 381
  S1_LDR: 382
  S1_MSV_POS: 383
  S1_MSV2_POS: 384
  S1_SAD1_POS: 385
  S1_SAD2_POS: 386
  S1_ACV_POS: 387
  S1_AP_P: 388
  S1_TT_LPAD1: 389


units:
  "GT":
    "GT_Load":
      "MW"
    "GT_Fuel consumtion":
      "Lb/Sec"
    "GT_Exhaust":
      "Lb/Sec"
    "GT_ExhaustPressure":
      "barg"
    "GT_RPM":
      "RPM"
    "Ambient Temp":
      "DEGF"
    "Relative_Humidity":
      "%"

  "HRSG":
    "HRSG Inlet Duct Temp":
      "DEGF"
    "HRSG Mod1 Temp":
      "DEGC"
    "HRSG Mod2 Temp":
      "DEGC"
    "HRSG Mod3 Temp":
      "DEGC"
    "HRSG Outlet Stack Temp":
      "DEGC"

  "SCR":
    "Ammonia Storage Level":
      "mm"
    "Ammonia Line P":
      "bar.g"
    "Compression Air Pressure":
      "bar.g"
    "Exhaust Gas Temp A/B":
      "DEGC"
    "Exhaust Gas Temp A/B/C":
      "DEGC"
    "Exhaust Gas Pressure A/B/C":
      "mbar.g"
    "Ammonia Injection":
      "kg/hr"
    "Ammonia Injection Control Valve":
      "%"
    "Inlet NO":
      "ppm"
    "Inlet NO2":
      "ppm"
    "Inlet O2":
      "%"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"
    "Stack NOx":
      "ppm"
    "Outlet O2":
      "%"
    "Ammonia Slip":
      "ppm"
    "Exhaust Gas Flow Rate":
      "m/s"
    "Inlet CO":
      "ppm"
    "Inlet THC":
      "ppm"
    "Outlet CO":
      "ppm"
    "Outlet THC":
      "ppm"
  "YPES":
    "Reducing Agent Storage":
      "mm"
    "Reducing Agent Injection":
      "kg/hr"
    "Reducing Agent Injection CV":
      "%"
    "HRSG Inlet Duct NO":
      "ppm"
    "HRSG Inlet Duct NO2":
      "ppm"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"

  "IODCS":
    "Dust Filter Pressure Diff":
      "mbar"
    "Dust Filter Temp":
      "DEGC"
    "HRSG Stack Dust":
      "ppm"
    "Filter Motor":
      "%"
