!!python/object:configs.config.Arguments

host: "192.168.8.100"
port: 501

first_incoming:
  100
timestamp_addr:
  250

coil_addr:
  1ZYR5311: 0
  1ZYR5312: 1
  1ZYR1331: 2
  1ZYR2331: 3
  1ZSR5401A: 4
  1ZSR5401B: 5
  1ZYR5471: 6
  1ZYR5472: 7
  1AUTSTSQ_ON: 8
  T1_L52GX: 9
  T2_L52GX: 10
  1ZSO1117: 11
  1ZSO1116: 12
  1ZSO1026: 13
  1ZSO1021: 14
  1ZSO2117: 15
  1ZSO2116: 16
  1ZSO2026: 17
  1ZSO2021: 18
  1XS5907: 19
  S1_L52GX: 20
  T1_L83TMSEL: 21
  T2_L83TMSEL: 22
  1SEQ223B-DONE: 23
  1ZSO1145: 24
  1ZSO2145: 25
  1ZSO1175: 26
  1ZSO2175: 27
  1ZSO5062: 28
  T1_L83EX: 29
  T2_L83EX: 30
  1TV1118-Mode: 31
  1TV2118-Mode: 32
  1TV1025-Mode: 33
  1TV2025-Mode: 34
  1G1STSQ-LEAD: 35
  1G2STSQ-LEAD: 36
  S1_L4: 37
  1G1STSQ-RDY: 38
  1G2STSQ-RDY: 39
  1H1STSQ-RDY: 40
  1H2STSQ-RDY: 41
  1BOPSTSQ-RDY: 42
  1STRDY-STSQ: 43
  1ZSO1148: 44
  1ZSO2148: 45
  1JYS101A: 46
  1JYS101B: 47
  1JYS201A: 48
  1JYS201B: 49
  1JYR101A: 50
  1JYR101B: 51
  1JYR201A: 52
  1JYR201B: 53
  T1_L33MDCF: 54
  T1_L89SSC: 55
  T1_L86GLT1_EVT: 56
  T1_L86GLT3_EVT: 57
  T1_L33CB5C: 58
  T1_L33CB6C: 59
  T1_L33CB7C: 60
  T1_L33CB8C: 61
  T1_L4SS_RUN: 62
  T1_L86GLT7_EVT: 63
  T1_L28FD: 64
  T1_L3: 65
  T1_L4EX_SS: 66
  T1_L89NDO: 67
  T2_L89SSC: 68
  T2_L86GLT1_EVT: 69
  T2_L86GLT3_EVT: 70
  T2_L33CB5C: 71
  T2_L33CB6C: 72
  T2_L33CB7C: 73
  T2_L33CB8C: 74
  T2_L4SS_RUN: 75
  T2_L86GLT7_EVT: 76
  T2_L28FD: 77
  T2_L3: 78
  T2_L4EX_SS: 79
  T2_L89NDO: 80
  S1_L26SS_PER: 81
  S1_L83CVS_C: 82
  S1_L39DEA: 83
  S1_L14HR: 84
  S1_L63IP_L_OK: 85
  S1_L26IS_L_OK: 86
  S1_L3CUST_PERM: 87
  S1_L33DRAIN_PER: 88
  S1_L30ECH_PER: 89
  S1_LLOAM: 90
  S1_L33MSV_O: 91
  S1_L33MSV2_O: 92
  S1_L33LRSV_O: 93
  S1_L33RRSV_O: 94
  S1_L33ASV_O: 95

reg_addr:
  1LT001: 0
  1PT101: 2
  1PT111: 4
  1FY111: 6
  1AIT132: 8
  1AIT135: 10
  1PT201: 12
  1PT211: 14
  1FY211: 16
  1AIT232: 18
  1AIT235: 20
  1AIT1832: 22
  1AIT2832: 24
  1CCGPS-SEC: 26
  1CCGPS-MIN: 28
  1CCGPS-HOUR: 30
  1CCGPS-DAYM: 32
  1CCGPS-MNTH: 34
  1CCGPS-YEAR: 36
  1TY5904: 38
  T1_DWATT: 40
  T2_DWATT: 42
  S1_DWATT: 44
  1FI5301-TT: 46
  1FI5302-TT: 48
  1LI1100: 50
  1LI2100: 52
  1LI1130: 54
  1LI2130: 56
  1LI1160: 58
  1LI2160: 60
  S1_EV_P_SCA: 62
  1PI1100: 64
  1PI2100: 66
  1PI1130: 68
  1ZT1071: 70
  1ZT1001: 72
  1PI2130: 74
  1ZT2071: 76
  1ZT2001: 78
  1FT111-RATE: 80
  1FT211-RATE: 82
  1AIT1831: 84
  1AIT2831: 86
  1PT5015: 88
  1TI1118: 90
  1TI2118: 92
  1PI1001: 94
  1PI2001: 96
  1TI1025: 98
  1TI2025: 100
  1ZT1072: 102
  1ZT2072: 104
  1ZT1061: 106
  1ZT2061: 108
  1TI1177: 110
  1TI2177: 112
  1PI1061: 114
  1PI2061: 116
  016-01829-OUT: 118
  016-00288-OUT: 120
  1FI5301: 122
  1FI5302: 124
  1CCTIME: 126
  1AIT134-COMP: 128
  1AIT234-COMP: 130
  1AIT131-COMP: 132
  1AIT231-COMP: 134
  1TI132: 136
  1TI232: 138
  T1_TNH_V: 140
  T1_ttxm: 142
  T1_CTIMR1: 144
  T1_FQG: 146
  T1_L90PSEL_CMD: 148
  T1_FTG: 150
  T1_CTIM: 152
  T1_AFPEP: 154
  DNL_MODE: 156
  T2_TNH_V: 158
  T2_ttxm: 160
  T2_CTIMR1: 162
  T2_FQG: 164
  T2_L90PSEL_CMD: 166
  T2_FTG: 168
  T2_CTIM: 172
  T2_AFPEP: 174
  DNL_MODE2: 176
  1STDL5477: 178
  S1_TNH_rpm: 180
  S1_IP_P: 182
  S1_TT_IS: 184
  S1_TT_1SBU1: 186
  S1_TT_1SBU2: 188
  S1_ECCENT: 190
  S1_TT_SSH: 192
  S1_V1_POS: 194
  S1_V1L_POS: 196
  S1_TT_LOCO: 198
  1STDL5472: 200
  1STDL5473: 202
  1STDL5474: 204
  1STDL5475: 206
  S1_LDR: 208
  S1_MSV_POS: 210
  S1_MSV2_POS: 212
  S1_SAD1_POS: 214
  S1_SAD2_POS: 216
  S1_ACV_POS: 218
  S1_AP_P: 220
  S1_TT_LPAD1: 222
  S1_INLET_DIFF: 224

units:
  "GT":
    "GT_Load":
      "MW"
    "GT_Fuel consumtion":
      "Lb/Sec"
    "GT_Exhaust":
      "Lb/Sec"
    "GT_ExhaustPressure":
      "barg"
    "GT_RPM":
      "RPM"
    "Ambient Temp":
      "DEGF"
    "Relative_Humidity":
      "%"

  "HRSG":
    "HRSG Inlet Duct Temp":
      "DEGF"
    "HRSG Mod1 Temp":
      "DEGC"
    "HRSG Mod2 Temp":
      "DEGC"
    "HRSG Mod3 Temp":
      "DEGC"
    "HRSG Outlet Stack Temp":
      "DEGC"

  "SCR":
    "Ammonia Storage Level":
      "mm"
    "Ammonia Line P":
      "bar.g"
    "Compression Air Pressure":
      "bar.g"
    "Exhaust Gas Temp A/B":
      "DEGC"
    "Exhaust Gas Temp A/B/C":
      "DEGC"
    "Exhaust Gas Pressure A/B/C":
      "mbar.g"
    "Ammonia Injection":
      "kg/hr"
    "Ammonia Injection Control Valve":
      "%"
    "Inlet NO":
      "ppm"
    "Inlet NO2":
      "ppm"
    "Inlet O2":
      "%"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"
    "Stack NOx":
      "ppm"
    "Outlet O2":
      "%"
    "Ammonia Slip":
      "ppm"
    "Exhaust Gas Flow Rate":
      "m/s"
    "Inlet CO":
      "ppm"
    "Inlet THC":
      "ppm"
    "Outlet CO":
      "ppm"
    "Outlet THC":
      "ppm"
  "YPES":
    "Reducing Agent Storage":
      "mm"
    "Reducing Agent Injection":
      "kg/hr"
    "Reducing Agent Injection CV":
      "%"
    "HRSG Inlet Duct NO":
      "ppm"
    "HRSG Inlet Duct NO2":
      "ppm"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"

  "IODCS":
    "Dust Filter Pressure Diff":
      "mbar"
    "Dust Filter Temp":
      "DEGC"
    "HRSG Stack Dust":
      "ppm"
    "Filter Motor":
      "%"
