!!python/object:configs.config.Arguments

hosts:
- ["192.168.0.8", 502]

first_incoming:
  0
timestamp_addr:
  250

coil_addr:
  1ZYR5311: 1
  1ZYR5312: 2
  1ZYR1331: 3
  1ZYR2331: 4
  1ZSR5401A: 5
  1ZSR5401B: 6
  1ZYR5471: 7
  1ZYR5472: 8
  1AUTSTSQ_ON: 9
  T1_L33CB1O: 10
  T1_L33CB2O: 11
  T1_L33CB3O: 12
  T1_L33CB4O: 13
  T1_L4SS_RUN: 14
  T1_L86GLT7_EVT: 15
  T1_L28FD: 16
  T1_L3: 17
  1ZSO1132: 18
  1ZSO1133: 19
  1ZSO1135: 20
  1ZSO1102: 21
  1ZSO1103: 22
  T2_L33CB1O: 23
  T2_L33CB2O: 24
  T2_L33CB3O: 25
  T2_L33CB4O: 26
  T2_L4SS_RUN: 27
  T2_L86GLT7_EVT: 28
  T2_L28FD: 29
  T2_L3: 30
  1ZSO2132: 31
  1ZSO2133: 32
  1ZSO2135: 33
  1ZSO2102: 34
  1ZSO2103: 35
  T1_L52GX: 36
  T2_L52GX: 37
  1ZSO1117: 38
  1ZSO1116: 39
  1ZSO1026: 40
  1ZSO1021: 41
  1ZSO2117: 42
  1ZSO2116: 43
  1ZSO2026: 44
  1ZSO2021: 45
  S1_L3CUST_PERM: 46
  S1_L33DRAIN_PER: 47
  S1_L3START_MAN: 48
  S1_L3START_AUTO: 49
  1XS5907: 50
  S1_L14HM: 51
  S1_L52GX: 52
  T1_L83TMSEL: 53
  T2_L83TMSEL: 54
  1SEQ223B-DONE: 55
  1ZSO1145: 56
  1ZSO2145: 57
  1ZSO1175: 58
  1ZSO2175: 59
  1ZSO5062: 60
  T1_L83EX: 61
  T2_L83EX: 62
  1TV1118-Mode: 63
  1TV2118-Mode: 64
  1TV1025-Mode: 65
  1TV2025-Mode: 66
  1G1STSQ-LEAD: 67
  1G2STSQ-LEAD: 68
  T1_L4EX_SS: 69
  T1_L89NDO: 70
  T1_L33MDCF: 71
  T1_L89SSC: 72
  T1_L86GLT1_EVT: 73
  T1_L86GLT3_EVT: 74
  T2_L4EX_SS: 75
  T2_L89NDO: 76
  T2_L89SSC: 77
  T2_L86GLT1_EVT: 78
  T2_L86GLT3_EVT: 79
  1LV1400-Mode: 80
  1LV1130-Mode: 81
  1LV1160-Mode: 82
  1LV2400-Mode: 83
  1LV2130-Mode: 84
  1LV2160-Mode: 85
  1ZSO1148: 86
  1ZSO2148: 87
  1G1STSQ-RDY: 88
  1G2STSQ-RDY: 89
  1H1STSQ-RDY: 90
  1H2STSQ-RDY: 91
  1BOPSTSQ-RDY: 92
  1STRDY-STSQ: 93
  1GTDL-1GT-RTU-BIT0: 94
  1GTDL-2GT-RTU-BIT0: 95
  1STDL-1ST-RTU-BIT0: 96

reg_addr:
  T1_CTIMR1: 301
  1TY5904: 303
  1STDL5477: 305
  T1_DWATT: 307
  T2_DWATT: 309
  S1_DWATT: 311
  T1_FQG: 313
  T2_FQG: 315
  1FI5301-TT: 317
  1FI5302-TT: 319
  1LI1100: 321
  1LI2100: 323
  1LI1130: 325
  1LI2130: 327
  1LI1160: 329
  1LI2160: 331
  S1_EV_P_SCA: 333
  1TE5417: 335
  1PI1100: 337
  1PI2100: 339
  T1_TNH_V: 341
  1PI1130: 343
  1ZT1071: 345
  1ZT1001: 347
  T2_TNH_V: 349
  1PI2130: 351
  1ZT2071: 353
  1ZT2001: 355
  1FT111-RATE: 357
  1FT211-RATE: 359
  1AIT1831: 361
  1AIT2831: 363
  1PT5035: 365
  1TE5034: 367
  1TE5036: 369
  S1_TNH_rpm: 371
  S1_IP_P: 373
  S1_TT_IS: 375
  S1_TT_1SBU1: 377
  S1_TT_1SBU2: 379
  S1_INLET_DIF: 381
  S1_ECCENT: 383
  S1_TT_SSH: 385
  S1_V1_POS: 387
  S1_V1L_POS: 389
  S1_TT_LOCO: 391
  1PT5015: 393
  1TI1118: 417
  1TI2118: 419
  1STDL5472: 399
  1STDL5473: 401
  1STDL5474: 403
  1STDL5475: 405
  1FI5321: 407
  T1_ttxm: 409
  T2_ttxm: 411
  1PI1001: 413
  1PI2001: 415
  S1_LDR: 421
  T1_FTG: 423
  T2_FTG: 425
  1ZT1072: 427
  1ZT2072: 429
  S1_ACV_POS: 431
  S1_AP_P: 433
  S1_TT_LPAS: 435
  1ZT1061: 437
  1ZT2061: 439
  1TI1177: 441
  1TI2177: 443
  1PT5106: 445
  1TE5031: 447
  1PI1061: 449
  T1_CTIM: 451
  T2_CTIM: 453
  T1_AFPEP: 455
  T2_AFPEP: 457
  S1_MSV_POS: 459
  S1_MSV2_POS: 461
  S1_LIV_POS: 463
  S1_RIV_POS: 465
  S1_SSV1A_POS: 467
  S1_SSV2A_POS: 469
  S1_SSV1B_POS: 471
  S1_SSV2B_POS: 473
  S1_SSV4A_POS: 475
  S1_SSV4B_POS: 477
  1FI5301: 479
  1FI5302: 481
  S1_SAD1_POS: 483
  S1_SAD2_POS: 485
  T1_L90PSEL_CMD: 487
  T2_L90PSEL_CMD: 489
  1CCTIME: 491
  undefined: 493
  1AIT134-COMP: 495
  1AIT234-COMP: 497


units:
  "GT":
    "GT_Load":
      "MW"
    "GT_Fuel consumtion":
      "Lb/Sec"
    "GT_Exhaust":
      "Lb/Sec"
    "GT_ExhaustPressure":
      "barg"
    "GT_RPM":
      "RPM"
    "Ambient Temp":
      "DEGF"
    "Relative_Humidity":
      "%"

  "HRSG":
    "HRSG Inlet Duct Temp":
      "DEGF"
    "HRSG Mod1 Temp":
      "DEGC"
    "HRSG Mod2 Temp":
      "DEGC"
    "HRSG Mod3 Temp":
      "DEGC"
    "HRSG Outlet Stack Temp":
      "DEGC"

  "SCR":
    "Ammonia Storage Level":
      "mm"
    "Ammonia Line P":
      "bar.g"
    "Compression Air Pressure":
      "bar.g"
    "Exhaust Gas Temp A/B":
      "DEGC"
    "Exhaust Gas Temp A/B/C":
      "DEGC"
    "Exhaust Gas Pressure A/B/C":
      "mbar.g"
    "Ammonia Injection":
      "kg/hr"
    "Ammonia Injection Control Valve":
      "%"
    "Inlet NO":
      "ppm"
    "Inlet NO2":
      "ppm"
    "Inlet O2":
      "%"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"
    "Stack NOx":
      "ppm"
    "Outlet O2":
      "%"
    "Ammonia Slip":
      "ppm"
    "Exhaust Gas Flow Rate":
      "m/s"
    "Inlet CO":
      "ppm"
    "Inlet THC":
      "ppm"
    "Outlet CO":
      "ppm"
    "Outlet THC":
      "ppm"
  "YPES":
    "Reducing Agent Storage":
      "mm"
    "Reducing Agent Injection":
      "kg/hr"
    "Reducing Agent Injection CV":
      "%"
    "HRSG Inlet Duct NO":
      "ppm"
    "HRSG Inlet Duct NO2":
      "ppm"
    "Outlet NO":
      "ppm"
    "Outlet NO2":
      "ppm"

  "IODCS":
    "Dust Filter Pressure Diff":
      "mbar"
    "Dust Filter Temp":
      "DEGC"
    "HRSG Stack Dust":
      "ppm"
    "Filter Motor":
      "%"
